# Generated by Django 5.2.16 on 2026-07-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "client",
                    models.CharField(default="BHP · Faena Spence", max_length=120),
                ),
                (
                    "general_status",
                    models.CharField(default="Operación normal", max_length=60),
                ),
                (
                    "general_status_detail",
                    models.CharField(default="Sin alertas críticas", max_length=120),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MitigationImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reduction_pct",
                    models.FloatField(help_text="Disminución estimada, p. ej. -24"),
                ),
                (
                    "without_mitigation",
                    models.FloatField(help_text="µg/m³N sin mitigación"),
                ),
                (
                    "with_mitigation",
                    models.FloatField(help_text="µg/m³N con mitigación actual"),
                ),
                ("simulated", models.BooleanField(default=True)),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitigation",
                        to="monitoring.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=40)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("delta", models.CharField(blank=True, max_length=20)),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("up", "up"), ("down", "down")],
                        max_length=10,
                    ),
                ),
                (
                    "delta_positive",
                    models.BooleanField(
                        default=True,
                        help_text="¿El delta es una buena noticia? (color verde)",
                    ),
                ),
                ("comparison", models.CharField(blank=True, max_length=60)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("simulated", models.BooleanField(default=False)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="monitoring.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_c", models.FloatField()),
                ("humidity_pct", models.FloatField()),
                ("wind_direction", models.CharField(max_length=10)),
                ("wind_speed_kmh", models.FloatField()),
                ("simulated", models.BooleanField(default=True)),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment",
                        to="monitoring.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="monitoring.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProcessPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("icon", models.CharField(default="factory", max_length=40)),
                ("has_sensor", models.BooleanField(default=True)),
                (
                    "pm10",
                    models.FloatField(
                        blank=True,
                        help_text="µg/m³N — SIMULADO (hoy no se captura)",
                        null=True,
                    ),
                ),
                ("simulated_pm10", models.BooleanField(default=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_points",
                        to="monitoring.area",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("supresor", "Supresor de polvo"),
                            ("humectador", "Humectador"),
                            ("filtro", "Filtro de mangas / Colector de polvo"),
                        ],
                        default="supresor",
                        max_length=20,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Patrones reales: DPSVxxxx, MSCPxxxx, EX-HUxx, SP-xx",
                        max_length=40,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "indicator_label",
                    models.CharField(
                        default="Estado Operativo",
                        help_text='"Estado Operativo" o "Eficiencia" según tarjeta',
                        max_length=40,
                    ),
                ),
                ("nozzles_installed", models.PositiveIntegerField(default=0)),
                ("nozzles_operative", models.PositiveIntegerField(default=0)),
                ("nozzles_running", models.PositiveIntegerField(default=0)),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("programada", "Detención programada por proyecto"),
                            ("falla", "Falla / rotura de cañería"),
                            ("fuera_proceso", "Fuera de proceso (cliente)"),
                            ("area_restringida", "Área restringida por terceros"),
                            ("solicitud_cliente", "Solicitud del cliente"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="monitoring.area",
                    ),
                ),
                (
                    "process_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systems",
                        to="monitoring.processpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critica", "Crítica"),
                            ("mayor", "Mayor"),
                            ("menor", "Menor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField()),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.plant",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="monitoring.system",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=40)),
                ("value", models.CharField(max_length=20)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("sparkline", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("simulated", models.BooleanField(default=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="monitoring.system",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Pm10Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range",
                    models.CharField(
                        choices=[("hoy", "Hoy"), ("7d", "7 días"), ("30d", "30 días")],
                        max_length=5,
                    ),
                ),
                ("labels", models.JSONField(default=list, help_text="Etiquetas eje X")),
                (
                    "current",
                    models.JSONField(default=list, help_text='Serie "Promedio planta"'),
                ),
                (
                    "previous",
                    models.JSONField(
                        default=list,
                        help_text='Serie comparativa "Ayer" / periodo anterior',
                    ),
                ),
                ("simulated", models.BooleanField(default=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pm10_series",
                        to="monitoring.plant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PM10 series",
                "unique_together": {("plant", "range")},
            },
        ),
    ]
