# Generated by Django 5.2.16 on 2026-07-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preventiva", "Preventiva"),
                            ("correctiva", "Correctiva"),
                            ("inspeccion", "Inspección"),
                        ],
                        default="preventiva",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_ejecucion", "En ejecución"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="abierta",
                        max_length=15,
                    ),
                ),
                ("technician", models.CharField(max_length=80)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_hours", models.FloatField(default=0)),
                ("description", models.CharField(max_length=250)),
                (
                    "tasks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tareas realizadas / por realizar",
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Registro fotográfico del operario: [{label, taken_at}]",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="monitoring.plant",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="monitoring.system",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
    ]
